// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/register/merchant": {
    params: {};
  };
  "/register/client": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/marketplace": {
    params: {};
  };
  "/marketplace/store/:merchantId": {
    params: {
      "merchantId": string;
    };
  };
  "/marketplace/:id": {
    params: {
      "id": string;
    };
  };
  "/checkout/:gigId": {
    params: {
      "gigId": string;
    };
  };
  "/booking/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/pesanan": {
    params: {};
  };
  "/pesanan/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/merchant/gigs": {
    params: {};
  };
  "/merchant/gigs/create": {
    params: {};
  };
  "/merchant/gigs/:id": {
    params: {
      "id": string;
    };
  };
  "/merchant/dashboard": {
    params: {};
  };
  "/merchant/messages": {
    params: {};
  };
  "/merchant/orders": {
    params: {};
  };
  "/merchant/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/merchant/transactions": {
    params: {};
  };
  "/merchant/associates": {
    params: {};
  };
  "/merchant/profile": {
    params: {};
  };
  "/merchant/onboarding": {
    params: {};
  };
  "/merchant/pending": {
    params: {};
  };
  "/merchant/rejected": {
    params: {};
  };
  "/merchant/approve": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/register/merchant" | "/register/client" | "/login" | "/marketplace" | "/marketplace/store/:merchantId" | "/marketplace/:id" | "/checkout/:gigId" | "/booking/:orderId" | "/pesanan" | "/pesanan/:orderId" | "/merchant/gigs" | "/merchant/gigs/create" | "/merchant/gigs/:id" | "/merchant/dashboard" | "/merchant/messages" | "/merchant/orders" | "/merchant/orders/:id" | "/merchant/transactions" | "/merchant/associates" | "/merchant/profile" | "/merchant/onboarding" | "/merchant/pending" | "/merchant/rejected" | "/merchant/approve";
  };
  "src/pages/auth/RegisterMerchant.tsx": {
    id: "src/pages/auth/RegisterMerchant";
    page: "/register/merchant";
  };
  "src/pages/auth/RegisterClient.tsx": {
    id: "src/pages/auth/RegisterClient";
    page: "/register/client";
  };
  "src/pages/auth/Login.tsx": {
    id: "src/pages/auth/Login";
    page: "/login";
  };
  "src/layouts/HomeLayout.tsx": {
    id: "src/layouts/HomeLayout";
    page: "/";
  };
  "src/pages/LandingPage.tsx": {
    id: "src/pages/LandingPage";
    page: "/";
  };
  "src/layouts/ClientLayout.tsx": {
    id: "src/layouts/ClientLayout";
    page: "/marketplace" | "/marketplace/store/:merchantId" | "/marketplace/:id" | "/checkout/:gigId" | "/booking/:orderId" | "/pesanan" | "/pesanan/:orderId";
  };
  "src/pages/client/Marketplace.tsx": {
    id: "src/pages/client/Marketplace";
    page: "/marketplace";
  };
  "src/pages/client/MerchantStore.tsx": {
    id: "src/pages/client/MerchantStore";
    page: "/marketplace/store/:merchantId";
  };
  "src/pages/client/ServiceDetail.tsx": {
    id: "src/pages/client/ServiceDetail";
    page: "/marketplace/:id";
  };
  "src/pages/client/Checkout.tsx": {
    id: "src/pages/client/Checkout";
    page: "/checkout/:gigId";
  };
  "src/pages/client/Booking.tsx": {
    id: "src/pages/client/Booking";
    page: "/booking/:orderId";
  };
  "src/pages/client/Orders.tsx": {
    id: "src/pages/client/Orders";
    page: "/pesanan";
  };
  "src/pages/client/OrderDetail.tsx": {
    id: "src/pages/client/OrderDetail";
    page: "/pesanan/:orderId";
  };
  "src/layouts/MerchantLayout.tsx": {
    id: "src/layouts/MerchantLayout";
    page: "/merchant/gigs" | "/merchant/gigs/create" | "/merchant/gigs/:id" | "/merchant/dashboard" | "/merchant/messages" | "/merchant/orders" | "/merchant/orders/:id" | "/merchant/transactions" | "/merchant/associates" | "/merchant/profile" | "/merchant/onboarding" | "/merchant/pending" | "/merchant/rejected" | "/merchant/approve";
  };
  "src/pages/merchant/Gigs.tsx": {
    id: "src/pages/merchant/Gigs";
    page: "/merchant/gigs";
  };
  "src/pages/merchant/AddGigs.tsx": {
    id: "src/pages/merchant/AddGigs";
    page: "/merchant/gigs/create";
  };
  "src/pages/merchant/GigsDetail.tsx": {
    id: "src/pages/merchant/GigsDetail";
    page: "/merchant/gigs/:id";
  };
  "src/pages/merchant/Dashboard.tsx": {
    id: "src/pages/merchant/Dashboard";
    page: "/merchant/dashboard";
  };
  "src/pages/merchant/Messages.tsx": {
    id: "src/pages/merchant/Messages";
    page: "/merchant/messages";
  };
  "src/pages/merchant/Orders.tsx": {
    id: "src/pages/merchant/Orders";
    page: "/merchant/orders";
  };
  "src/pages/merchant/OrderDetail.tsx": {
    id: "src/pages/merchant/OrderDetail";
    page: "/merchant/orders/:id";
  };
  "src/pages/merchant/Transactions.tsx": {
    id: "src/pages/merchant/Transactions";
    page: "/merchant/transactions";
  };
  "src/pages/merchant/Associates.tsx": {
    id: "src/pages/merchant/Associates";
    page: "/merchant/associates";
  };
  "src/pages/merchant/StoreProfile.tsx": {
    id: "src/pages/merchant/StoreProfile";
    page: "/merchant/profile";
  };
  "src/pages/merchant/MerchantOnBoarding.tsx": {
    id: "src/pages/merchant/MerchantOnBoarding";
    page: "/merchant/onboarding";
  };
  "src/pages/merchant/MerchantPending.tsx": {
    id: "src/pages/merchant/MerchantPending";
    page: "/merchant/pending";
  };
  "src/pages/merchant/MerchantRejected.tsx": {
    id: "src/pages/merchant/MerchantRejected";
    page: "/merchant/rejected";
  };
  "src/pages/merchant/MerchantActivated.tsx": {
    id: "src/pages/merchant/MerchantActivated";
    page: "/merchant/approve";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "src/pages/auth/RegisterMerchant": typeof import("./app/src/pages/auth/RegisterMerchant.tsx");
  "src/pages/auth/RegisterClient": typeof import("./app/src/pages/auth/RegisterClient.tsx");
  "src/pages/auth/Login": typeof import("./app/src/pages/auth/Login.tsx");
  "src/layouts/HomeLayout": typeof import("./app/src/layouts/HomeLayout.tsx");
  "src/pages/LandingPage": typeof import("./app/src/pages/LandingPage.tsx");
  "src/layouts/ClientLayout": typeof import("./app/src/layouts/ClientLayout.tsx");
  "src/pages/client/Marketplace": typeof import("./app/src/pages/client/Marketplace.tsx");
  "src/pages/client/MerchantStore": typeof import("./app/src/pages/client/MerchantStore.tsx");
  "src/pages/client/ServiceDetail": typeof import("./app/src/pages/client/ServiceDetail.tsx");
  "src/pages/client/Checkout": typeof import("./app/src/pages/client/Checkout.tsx");
  "src/pages/client/Booking": typeof import("./app/src/pages/client/Booking.tsx");
  "src/pages/client/Orders": typeof import("./app/src/pages/client/Orders.tsx");
  "src/pages/client/OrderDetail": typeof import("./app/src/pages/client/OrderDetail.tsx");
  "src/layouts/MerchantLayout": typeof import("./app/src/layouts/MerchantLayout.tsx");
  "src/pages/merchant/Gigs": typeof import("./app/src/pages/merchant/Gigs.tsx");
  "src/pages/merchant/AddGigs": typeof import("./app/src/pages/merchant/AddGigs.tsx");
  "src/pages/merchant/GigsDetail": typeof import("./app/src/pages/merchant/GigsDetail.tsx");
  "src/pages/merchant/Dashboard": typeof import("./app/src/pages/merchant/Dashboard.tsx");
  "src/pages/merchant/Messages": typeof import("./app/src/pages/merchant/Messages.tsx");
  "src/pages/merchant/Orders": typeof import("./app/src/pages/merchant/Orders.tsx");
  "src/pages/merchant/OrderDetail": typeof import("./app/src/pages/merchant/OrderDetail.tsx");
  "src/pages/merchant/Transactions": typeof import("./app/src/pages/merchant/Transactions.tsx");
  "src/pages/merchant/Associates": typeof import("./app/src/pages/merchant/Associates.tsx");
  "src/pages/merchant/StoreProfile": typeof import("./app/src/pages/merchant/StoreProfile.tsx");
  "src/pages/merchant/MerchantOnBoarding": typeof import("./app/src/pages/merchant/MerchantOnBoarding.tsx");
  "src/pages/merchant/MerchantPending": typeof import("./app/src/pages/merchant/MerchantPending.tsx");
  "src/pages/merchant/MerchantRejected": typeof import("./app/src/pages/merchant/MerchantRejected.tsx");
  "src/pages/merchant/MerchantActivated": typeof import("./app/src/pages/merchant/MerchantActivated.tsx");
};