// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "src/layouts/HomeLayout.tsx": {
    id: "src/layouts/HomeLayout";
    page: "/";
  };
  "src/pages/LandingPage.tsx": {
    id: "src/pages/LandingPage";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "src/layouts/HomeLayout": typeof import("./app/src/layouts/HomeLayout.tsx");
  "src/pages/LandingPage": typeof import("./app/src/pages/LandingPage.tsx");
};